FROM ubuntu:25.10@sha256:a61c057b4f69200ecf031519a20db79b8683837ba1dc2a59458d333eb75b174d

ENV LANG=C.UTF-8

# Install the latest stable version of Rust and cargo with the deny tool
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y curl gcc libssl-dev openssl pkg-config && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    /root/.cargo/bin/cargo install --locked cargo-deny && \
    apt-get clean
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app
COPY . .

RUN cargo --help

ENTRYPOINT [ "/app/run_static_check.sh" ]
CMD [ "--local" ]
