FROM ubuntu:25.04@sha256:79efa276fdefa2ee3911db29b0608f8c0561c347ec3f4d4139980d43b168d991

ENV LANG=C.UTF-8

# Install the latest stable version of Rust and cargo with the deny tool
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y curl gcc libssl-dev openssl pkg-config && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    /root/.cargo/bin/cargo install --locked cargo-deny && \
    apt-get clean
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app
COPY . .

RUN cargo --help

ENTRYPOINT [ "/app/run_static_check.sh" ]
CMD [ "--local" ]
