name: MX Electrix API Static Check

on:
    push:
        branches: [ $default-branch, $protected-branches ]
    pull_request:
        branches: [ $default-branch ]
    workflow_dispatch:

jobs:

    cargo-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Run cargo check
              run: cargo check --release

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Run unit tests
              run: cargo test --release

    cargo-clippy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Install clippy
              run: rustup component add clippy

            - name: Run cargo clippy
              run: cargo clippy --release -- -D warnings -W clippy::all -W clippy::pedantic -W clippy::nursery

    cargo-deny:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              run: rustup toolchain install stable --profile minimal

            - name: Install cargo-deny
              run: cargo install --locked cargo-deny

            - name: Run cargo deny
              run: cargo deny --all-features --log-level error check
